### ISSUE TITLE
"You must build your code with position independent code if Qt was built with -reduce-relocations. "

### ISSUE THREAD

**Issue by edent** [biometrics/openbr#83]
Trying to compile on Ubuntu (12.04 64 bit), I'm getting a strange error

```
Building CXX object app/examples/CMakeFiles/age_estimation.dir/age_estimation.cpp.o
In file included from /usr/include/qt5/QtCore/qnamespace.h:45:0,
                 from /usr/include/qt5/QtCore/qobjectdefs.h:45,
                 from /usr/include/qt5/QtCore/qobject.h:47,
                 from /usr/include/qt5/QtCore/qcoreapplication.h:45,
                 from /usr/include/qt5/QtCore/QCoreApplication:1,
                 from /home/edent/git/openbr/app/br/br.cpp:17:
/usr/include/qt5/QtCore/qglobal.h:1079:4: error: #error "You must build your code with position independent code if Qt was built with -reduce-relocations. " "Compile your code with -fPIC or -fPIE."
```

I'm following the instructions at http://openbiometrics.org/doxygen/latest/linux_all.html and have all the correct dependencies etc installed.

Am I missing something obvious?
