### ISSUE TITLE
Fails to build with OpenCV 3.2.0 

### ISSUE THREAD

**Issue by pinaa** [biometrics/openbr#578]
I modified openbr/CMakeLists.txt so I could compile the code by changing the line,

    find_package(OpenCV 2.4.5 REQUIRED) 

with

    find_package(OpenCV 3.2.0 REQUIRED)
However, it breaks on boost.h at the definition of struct CascadeBoostParams : CvBoostParams {..};"
with,
boost.h:35:1: error: expected class-name before ‘{’ token
   35 | {
      | ^
because CvBoostParams is not defined.
I really didn't want to install OpenCV 2.4.5. Is it possible to get build it with 3.2.0?
My OS is Ubuntu 20.04.1 LTS with the latest utils.

Thanks,
Art
